version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: postgres_blog
    restart: always
    environment:
      POSTGRES_USER: blog_user
      POSTGRES_PASSWORD: '@BlogP@ss2024'
      POSTGRES_DB: blog_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog-network

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube_blog
    restart: always
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar_admin
      SONAR_JDBC_PASSWORD: '@SonarSecure123'
    depends_on:
      - postgres
    networks:
      - blog-network

volumes:
  postgres_data:

networks:
  blog-network:
    driver: bridge
